[versions]
kotlin = "2.1.10"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version = "8.3.5" }
licensee = { id = "app.cash.licensee", version = "1.12.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.7" }
mavencentral = { id = "io.github.hfhbd.mavencentral", version = "0.0.14" }
